name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Dependencies
        run: cd web && npm install

      - name: Run Unit Tests
        run: cd web && npm run test

        
      - name: Build Web App
        run: cd web && npm run build
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}

      - name: Deploy Firestore Rules
        env:
          # Use the same service account as hosting
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SPOF_IO }}
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT" > service-account.json
          export GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/service-account.json
          npx firebase-tools deploy --only firestore:rules --project spof-io --json
          rm service-account.json

      - name: Deploy Firestore Rules
        env:
          # Use the same service account as hosting
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SPOF_IO }}
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT" > service-account.json
          export GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/service-account.json
          npx firebase-tools deploy --only firestore:rules --project spof-io --json
          rm service-account.json

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SPOF_IO }}
          channelId: live
          projectId: spof-io
          target: skahl-ui
